var json_village_1_5 = {
"type": "FeatureCollection",
"name": "village_1_5",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "nom_lieu": "MOKOLO 5" }, "geometry": { "type": "Point", "coordinates": [ 11.50081, 3.87634 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "Briqueterie EST 2" }, "geometry": { "type": "Point", "coordinates": [ 11.51046, 3.88136 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "Mballa V" }, "geometry": { "type": "Point", "coordinates": [ 11.53242, 3.89755 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "ETOA MEKI" }, "geometry": { "type": "Point", "coordinates": [ 11.52547, 3.88245 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "Mballa VII" }, "geometry": { "type": "Point", "coordinates": [ 11.52683, 3.91411 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "Briqueterie est 4" }, "geometry": { "type": "Point", "coordinates": [ 11.51072, 3.8779 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NKOMKANA II" }, "geometry": { "type": "Point", "coordinates": [ 11.49604, 3.88687 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MOKOLO2" }, "geometry": { "type": "Point", "coordinates": [ 11.49687, 3.87768 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "azegue 2" }, "geometry": { "type": "Point", "coordinates": [ 11.49411, 3.87607 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "azegue 4" }, "geometry": { "type": "Point", "coordinates": [ 11.49376, 3.87861 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "EKOUDOU 2" }, "geometry": { "type": "Point", "coordinates": [ 11.50451, 3.87776 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "EBANG 1" }, "geometry": { "type": "Point", "coordinates": [ 11.55795, 4.00558 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MKOMKANA III" }, "geometry": { "type": "Point", "coordinates": [ 11.4951, 3.88367 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "Briqueterie Est 3" }, "geometry": { "type": "Point", "coordinates": [ 11.50916, 3.88065 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "elig-effa5" }, "geometry": { "type": "Point", "coordinates": [ 11.50352, 3.87213 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "BITENG" }, "geometry": { "type": "Point", "coordinates": [ 11.56262, 3.8497 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NGOA-EKELE III" }, "geometry": { "type": "Point", "coordinates": [ 11.50033, 3.85427 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NGOA-EKELLE OBILI  II" }, "geometry": { "type": "Point", "coordinates": [ 11.49276, 3.85282 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NKOMKANA 1" }, "geometry": { "type": "Point", "coordinates": [ 11.49915, 3.88224 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "elig-effa6" }, "geometry": { "type": "Point", "coordinates": [ 11.50261, 3.87103 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NSAM 2 (YDE 3)" }, "geometry": { "type": "Point", "coordinates": [ 11.50871, 3.826 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "ODZA II" }, "geometry": { "type": "Point", "coordinates": [ 11.52578, 3.80121 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "Briqueterie centre 2" }, "geometry": { "type": "Point", "coordinates": [ 11.510114, 3.87569 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "Briqueterie centre 1" }, "geometry": { "type": "Point", "coordinates": [ 11.507, 3.87678 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NKOMKANA I" }, "geometry": { "type": "Point", "coordinates": [ 11.49918, 3.8823 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MADAGASCAR 2" }, "geometry": { "type": "Point", "coordinates": [ 11.49546, 3.88064 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MADAGASCAR 1" }, "geometry": { "type": "Point", "coordinates": [ 11.49546, 3.88064 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MELEN IX" }, "geometry": { "type": "Point", "coordinates": [ 11.49448, 3.86386 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MEYOS" }, "geometry": { "type": "Point", "coordinates": [ 11.55741, 4.01862 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "EBANG 2" }, "geometry": { "type": "Point", "coordinates": [ 11.55803, 4.01131 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "AKAK 1" }, "geometry": { "type": "Point", "coordinates": [ 11.55749, 3.99466 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NKOZOA" }, "geometry": { "type": "Point", "coordinates": [ 11.54305, 3.96689 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MBALLA VI" }, "geometry": { "type": "Point", "coordinates": [ 11.53045, 3.89191 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MBALLA I" }, "geometry": { "type": "Point", "coordinates": [ 11.52197, 3.89571 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NYOM I" }, "geometry": { "type": "Point", "coordinates": [ 11.52145, 3.94735 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "OKOLO" }, "geometry": { "type": "Point", "coordinates": [ 11.51588, 3.93813 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "EKOMBITIE" }, "geometry": { "type": "Point", "coordinates": [ 11.51679, 3.94339 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "OLEMBE 1" }, "geometry": { "type": "Point", "coordinates": [ 11.52403, 3.95054 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MBALLA 3A" }, "geometry": { "type": "Point", "coordinates": [ 11.52563, 3.90288 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "OLEMBE 2" }, "geometry": { "type": "Point", "coordinates": [ 11.52797, 3.95346 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MBALLA 3B" }, "geometry": { "type": "Point", "coordinates": [ 11.52466, 3.9116 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MBALLA 4" }, "geometry": { "type": "Point", "coordinates": [ 11.53412, 3.90176 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MBALLA 3E" }, "geometry": { "type": "Point", "coordinates": [ 11.53637, 3.93001 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "EMANA CARREFOUR" }, "geometry": { "type": "Point", "coordinates": [ 11.523659, 3.919636 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MBALLA 2" }, "geometry": { "type": "Point", "coordinates": [ 11.52293, 3.89661 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NKOLMBONG" }, "geometry": { "type": "Point", "coordinates": [ 11.54204, 3.93047 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MBALLA 3C" }, "geometry": { "type": "Point", "coordinates": [ 11.52981, 3.91737 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "EMANA CENTRE" }, "geometry": { "type": "Point", "coordinates": [ 11.51871, 3.9229 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "DJOUNGOLO 4" }, "geometry": { "type": "Point", "coordinates": [ 11.52491, 3.8882 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "DJOUNGOLO 3" }, "geometry": { "type": "Point", "coordinates": [ 11.52305, 3.89198 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "konteng" }, "geometry": { "type": "Point", "coordinates": [ 11.481472244000031, 3.904210100000058 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "Ekoudou VI" }, "geometry": { "type": "Point", "coordinates": [ 11.5136, 3.8609 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "Briquetterie Ouest" }, "geometry": { "type": "Point", "coordinates": [ 11.50789, 3.87463 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MOKOLO4" }, "geometry": { "type": "Point", "coordinates": [ 11.49948, 3.87656 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MOKOLO3" }, "geometry": { "type": "Point", "coordinates": [ 11.49858, 3.87602 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "OLIGA" }, "geometry": { "type": "Point", "coordinates": [ 11.49293, 3.90194 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MESSA PLATEAU" }, "geometry": { "type": "Point", "coordinates": [ 11.49243, 3.88932 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MESSA EKOAZONG" }, "geometry": { "type": "Point", "coordinates": [ 11.492773, 3.88808 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MESSA ANGONO" }, "geometry": { "type": "Point", "coordinates": [ 11.4869, 3.8882 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "FEBE VILLAGE" }, "geometry": { "type": "Point", "coordinates": [ 11.48066, 3.91406 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MESSA NKOABA'A" }, "geometry": { "type": "Point", "coordinates": [ 11.49161, 3.88274 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MOKOLO 6" }, "geometry": { "type": "Point", "coordinates": [ 11.50226, 3.87442 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "EKOUDOU 1" }, "geometry": { "type": "Point", "coordinates": [ 11.50256, 3.87668 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MELEN II" }, "geometry": { "type": "Point", "coordinates": [ 11.53033, 3.86838 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MELEN 8 B" }, "geometry": { "type": "Point", "coordinates": [ 11.49186, 3.856559 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "AHALA 2" }, "geometry": { "type": "Point", "coordinates": [ 11.49534, 3.79678 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MFOUNDASSI 7" }, "geometry": { "type": "Point", "coordinates": [ 11.51899, 3.85199 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NGOA-EKELLE OBILI 4" }, "geometry": { "type": "Point", "coordinates": [ 11.49578, 3.8493 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NGOA-EKELLE OBILI 3" }, "geometry": { "type": "Point", "coordinates": [ 11.49345, 3.85146 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "nkoldongo 2" }, "geometry": { "type": "Point", "coordinates": [ 11.52507, 3.85774 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MELEN IV" }, "geometry": { "type": "Point", "coordinates": [ 11.4963, 3.86701 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "Nkolndongo 14" }, "geometry": { "type": "Point", "coordinates": [ 11.52606, 3.85974 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "Nkoldongo 3" }, "geometry": { "type": "Point", "coordinates": [ 11.52439, 3.85787 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "nkolndongo 5" }, "geometry": { "type": "Point", "coordinates": [ 11.5238, 3.85454 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "Nkolndongo 1" }, "geometry": { "type": "Point", "coordinates": [ 11.5267, 3.85917 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MENDONG" }, "geometry": { "type": "Point", "coordinates": [ 11.47172, 3.83378 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "KODENGUI II" }, "geometry": { "type": "Point", "coordinates": [ 11.53749, 3.8521 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NKOLDONGO IV" }, "geometry": { "type": "Point", "coordinates": [ 11.52245, 3.85549 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NDAMVOUT" }, "geometry": { "type": "Point", "coordinates": [ 11.51744, 3.83882 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MINKAN" }, "geometry": { "type": "Point", "coordinates": [ 11.51579, 3.77975 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MVAN SUD" }, "geometry": { "type": "Point", "coordinates": [ 11.52473, 3.82214 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "Mvan nord" }, "geometry": { "type": "Point", "coordinates": [ 11.51577, 3.77962 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "KONG" }, "geometry": { "type": "Point", "coordinates": [ 11.54941, 3.88303 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "ABOME" }, "geometry": { "type": "Point", "coordinates": [ 11.50832, 3.78366 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "DAKAR1" }, "geometry": { "type": "Point", "coordinates": [ 11.51169, 3.83905 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "AWAE5" }, "geometry": { "type": "Point", "coordinates": [ 11.52283, 3.84937 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "EWONKANG" }, "geometry": { "type": "Point", "coordinates": [ 11.5525, 3.82342 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MBOG ABANG" }, "geometry": { "type": "Point", "coordinates": [ 11.53115, 3.80641 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "EKOUNOU 4" }, "geometry": { "type": "Point", "coordinates": [ 11.518089, 3.83072 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "EKOUMDOUM" }, "geometry": { "type": "Point", "coordinates": [ 11.54289, 3.81423 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "ODZA III" }, "geometry": { "type": "Point", "coordinates": [ 11.52636, 3.80114 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "ODZA I" }, "geometry": { "type": "Point", "coordinates": [ 11.52473, 3.78684 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "essos sud 3" }, "geometry": { "type": "Point", "coordinates": [ 11.55165, 3.87744 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "kikoa" }, "geometry": { "type": "Point", "coordinates": [ 11.55337, 3.88578 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MEYONG NDZENGUE" }, "geometry": { "type": "Point", "coordinates": [ 11.53701, 3.88427 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "DJOUNGOLO 8" }, "geometry": { "type": "Point", "coordinates": [ 11.52834, 3.86378 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "DJOUNGOLO 7" }, "geometry": { "type": "Point", "coordinates": [ 11.52918, 3.86509 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "DJOUNGOLO 6" }, "geometry": { "type": "Point", "coordinates": [ 11.52991, 3.86959 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "DJOUNGOLO 5" }, "geometry": { "type": "Point", "coordinates": [ 11.53034, 3.86835 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "DJOUNGOLO 9" }, "geometry": { "type": "Point", "coordinates": [ 11.53301, 3.86343 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "ELIG OGMBA NSI" }, "geometry": { "type": "Point", "coordinates": [ 11.53313, 3.87634 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "ESSOS CENTRE 1" }, "geometry": { "type": "Point", "coordinates": [ 11.53482, 3.87144 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "BELIBI NDOMO" }, "geometry": { "type": "Point", "coordinates": [ 11.55459, 3.90054 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NGOUSSO I" }, "geometry": { "type": "Point", "coordinates": [ 11.5449, 3.89092 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "essos centre 3" }, "geometry": { "type": "Point", "coordinates": [ 11.54673, 3.87647 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "essos nord 1" }, "geometry": { "type": "Point", "coordinates": [ 11.53702, 3.87506 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "essos centre 2" }, "geometry": { "type": "Point", "coordinates": [ 11.53366, 3.86861 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NGOUSSO NTEM" }, "geometry": { "type": "Point", "coordinates": [ 11.54283, 3.9008 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NGOUSSO 2" }, "geometry": { "type": "Point", "coordinates": [ 11.55086, 3.89762 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NGOUSSO 3" }, "geometry": { "type": "Point", "coordinates": [ 11.54194, 3.9083 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "elig-effa7" }, "geometry": { "type": "Point", "coordinates": [ 11.50037, 3.87097 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "Eba'a" }, "geometry": { "type": "Point", "coordinates": [ 11.48211, 3.86276 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "Ekoudou VI" }, "geometry": { "type": "Point", "coordinates": [ 11.5136, 3.8609 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "ELIG-EFFA 4" }, "geometry": { "type": "Point", "coordinates": [ 11.49182, 3.87232 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MELEN 8C" }, "geometry": { "type": "Point", "coordinates": [ 11.48866, 3.85356 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "AKOK NDOE 2" }, "geometry": { "type": "Point", "coordinates": [ 11.46321, 3.84964 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MELEN 7B" }, "geometry": { "type": "Point", "coordinates": [ 11.4918, 3.86675 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MELEN VII A" }, "geometry": { "type": "Point", "coordinates": [ 11.4956, 3.8645 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MELEN V" }, "geometry": { "type": "Point", "coordinates": [ 11.50435, 3.86764 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "melen 1" }, "geometry": { "type": "Point", "coordinates": [ 11.50408, 3.86423 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "melen 6" }, "geometry": { "type": "Point", "coordinates": [ 11.49323, 3.86292 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "elig-effa III" }, "geometry": { "type": "Point", "coordinates": [ 11.49841, 3.87031 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "melen 3" }, "geometry": { "type": "Point", "coordinates": [ 11.49946, 3.86346 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "OYOM-ABANG IV" }, "geometry": { "type": "Point", "coordinates": [ 11.47017, 3.87596 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NKOLSO'O" }, "geometry": { "type": "Point", "coordinates": [ 11.47444, 3.87179 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NDAMVOUTH II" }, "geometry": { "type": "Point", "coordinates": [ 11.45801, 3.87317 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NKOLBISSON CETRE" }, "geometry": { "type": "Point", "coordinates": [ 11.44803, 3.87694 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NGOULMEKONG" }, "geometry": { "type": "Point", "coordinates": [ 11.45941, 3.87951 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "EKOREZOCK" }, "geometry": { "type": "Point", "coordinates": [ 11.45421, 3.88613 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "EKOUDOU III" }, "geometry": { "type": "Point", "coordinates": [ 11.50546, 3.87904 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "TSINGA2" }, "geometry": { "type": "Point", "coordinates": [ 11.50771, 3.88296 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NTOUGOU I" }, "geometry": { "type": "Point", "coordinates": [ 11.5036, 3.89814 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MESSA MEZALA" }, "geometry": { "type": "Point", "coordinates": [ 11.498004, 3.873597 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "AZEGUE III" }, "geometry": { "type": "Point", "coordinates": [ 11.4964, 3.87483 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "EKOUDOU IV" }, "geometry": { "type": "Point", "coordinates": [ 11.50685, 3.87791 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "EKOUDOU VII" }, "geometry": { "type": "Point", "coordinates": [ 11.50667, 3.87619 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "EKOUDOU V" }, "geometry": { "type": "Point", "coordinates": [ 11.50564, 3.87739 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NKOMKANA III" }, "geometry": { "type": "Point", "coordinates": [ 11.49519, 3.88369 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "Mokolo 7" }, "geometry": { "type": "Point", "coordinates": [ 11.49826, 3.87771 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MADAGASCAR III" }, "geometry": { "type": "Point", "coordinates": [ 11.49463, 3.87955 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MADAGASCAR 4" }, "geometry": { "type": "Point", "coordinates": [ 11.49518, 3.87872 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "Mokolo 1" }, "geometry": { "type": "Point", "coordinates": [ 11.50596, 3.88284 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "AWAE 1" }, "geometry": { "type": "Point", "coordinates": [ 11.52389, 3.85164 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "DJOUNGOLO 2" }, "geometry": { "type": "Point", "coordinates": [ 11.52215, 3.88685 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NSIMEYONG 3" }, "geometry": { "type": "Point", "coordinates": [ 11.48944, 3.81517 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "EKIE-SUD" }, "geometry": { "type": "Point", "coordinates": [ 11.54343, 3.83092 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "DJOUNGOLO 1" }, "geometry": { "type": "Point", "coordinates": [ 11.52437, 3.87317 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NSAM 1" }, "geometry": { "type": "Point", "coordinates": [ 11.51048, 3.83178 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MFOUNDASSI VII" }, "geometry": { "type": "Point", "coordinates": [ 11.51897, 3.85197 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NGOA-EKELE II" }, "geometry": { "type": "Point", "coordinates": [ 11.50479, 3.85563 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "ELOUMDEN II" }, "geometry": { "type": "Point", "coordinates": [ 11.499331, 3.814864 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "BASTOS" }, "geometry": { "type": "Point", "coordinates": [ 11.51172, 3.89222 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NTOUGOU 2" }, "geometry": { "type": "Point", "coordinates": [ 11.50155, 3.88188 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "EKOUNOU 1" }, "geometry": { "type": "Point", "coordinates": [ 11.52768, 3.84519 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MFOUNDASSI IV" }, "geometry": { "type": "Point", "coordinates": [ 11.52056, 3.84992 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "EKOUNOU III" }, "geometry": { "type": "Point", "coordinates": [ 11.52069, 3.84261 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MFANDENA  I" }, "geometry": { "type": "Point", "coordinates": [ 11.53073, 3.88544 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NLONGKAK   I" }, "geometry": { "type": "Point", "coordinates": [ 11.5194, 3.88815 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NLONGKAK II" }, "geometry": { "type": "Point", "coordinates": [ 11.51467, 3.88673 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "AZEGUE I" }, "geometry": { "type": "Point", "coordinates": [ 11.4934, 3.87294 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NKOL BIKOK 2" }, "geometry": { "type": "Point", "coordinates": [ 11.49142, 3.86878 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "cite verte" }, "geometry": { "type": "Point", "coordinates": [ 11.49415, 3.87178 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "Tsinga 1" }, "geometry": { "type": "Point", "coordinates": [ 11.50044, 3.88819 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "Briqueterie Est I" }, "geometry": { "type": "Point", "coordinates": [ 11.50809, 3.88029 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "Messa carrière" }, "geometry": { "type": "Point", "coordinates": [ 11.48911, 3.88401 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MELEN 8A" }, "geometry": { "type": "Point", "coordinates": [ 11.49315, 3.85882 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NKOLMESSENG I" }, "geometry": { "type": "Point", "coordinates": [ 11.46404, 3.7373 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NSIMEYONG 2" }, "geometry": { "type": "Point", "coordinates": [ 11.48698, 3.82895 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NGOA-EKELLE OBILI 1" }, "geometry": { "type": "Point", "coordinates": [ 11.49185, 3.84978 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "AHALA I" }, "geometry": { "type": "Point", "coordinates": [ 11.50188, 3.80986 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NSIMEYONG I" }, "geometry": { "type": "Point", "coordinates": [ 11.49935, 3.83876 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MEKOUMBOU II" }, "geometry": { "type": "Point", "coordinates": [ 11.45467, 3.74496 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "AFAN-OYOA III" }, "geometry": { "type": "Point", "coordinates": [ 11.46422, 3.74984 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NKOLMESSENG 3" }, "geometry": { "type": "Point", "coordinates": [ 11.56647, 3.89109 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "OLEZOA" }, "geometry": { "type": "Point", "coordinates": [ 11.51492, 3.84706 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "EFOULAN" }, "geometry": { "type": "Point", "coordinates": [ 11.50699, 3.83271 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NLONG MVOLYE" }, "geometry": { "type": "Point", "coordinates": [ 11.5006, 3.84531 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MEKOUMBOU 1" }, "geometry": { "type": "Point", "coordinates": [ 11.45455, 3.73103 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "AFAN-OYOA 2" }, "geometry": { "type": "Point", "coordinates": [ 11.47562, 3.76237 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "AFAN-OYOA 1" }, "geometry": { "type": "Point", "coordinates": [ 11.47337, 3.75791 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "OBOBOGO" }, "geometry": { "type": "Point", "coordinates": [ 11.50326, 3.82431 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "DAKAR 2" }, "geometry": { "type": "Point", "coordinates": [ 11.51192, 3.83757 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "Etoa carriere" }, "geometry": { "type": "Point", "coordinates": [ 11.47792, 3.78944 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MIMBOMAN I EST" }, "geometry": { "type": "Point", "coordinates": [ 11.54967, 3.8618 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MIMBOMAN I CENTRE" }, "geometry": { "type": "Point", "coordinates": [ 11.54145, 3.86606 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MIMBOMAN I SUD" }, "geometry": { "type": "Point", "coordinates": [ 11.53963, 3.86672 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "Mimboman plateau" }, "geometry": { "type": "Point", "coordinates": [ 11.54425, 3.86886 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MIMBOMAN II NORD" }, "geometry": { "type": "Point", "coordinates": [ 11.5685, 3.87028 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MIMBOMAN III" }, "geometry": { "type": "Point", "coordinates": [ 11.55747, 3.85951 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MIMBOMAN II SUD" }, "geometry": { "type": "Point", "coordinates": [ 11.55201, 3.86702 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "KONDENGUI 4" }, "geometry": { "type": "Point", "coordinates": [ 11.54365, 3.8575 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NTOUESSONG" }, "geometry": { "type": "Point", "coordinates": [ 11.54656, 3.854 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "KONDENGUI I - EST" }, "geometry": { "type": "Point", "coordinates": [ 11.53085, 3.85242 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "KONDENGUI 3" }, "geometry": { "type": "Point", "coordinates": [ 11.53819, 3.85339 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "KONDENGUI I OUEST" }, "geometry": { "type": "Point", "coordinates": [ 11.53427, 3.85245 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NKOLDONGO XI" }, "geometry": { "type": "Point", "coordinates": [ 11.53468, 3.85882 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NKOLDONGO 12" }, "geometry": { "type": "Point", "coordinates": [ 11.53598, 3.86091 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NKOLDONGO 10" }, "geometry": { "type": "Point", "coordinates": [ 11.52916, 3.85568 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "Nkoldongo VIII" }, "geometry": { "type": "Point", "coordinates": [ 11.53362, 3.8556 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MFOUNDASSI I" }, "geometry": { "type": "Point", "coordinates": [ 11.51982, 3.84959 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NKOLDONGO 13" }, "geometry": { "type": "Point", "coordinates": [ 11.52883, 3.858 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NKOLDONGO VI" }, "geometry": { "type": "Point", "coordinates": [ 11.52455, 3.85363 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NKOMO I" }, "geometry": { "type": "Point", "coordinates": [ 11.55126, 3.83776 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MESSAMENDONGO" }, "geometry": { "type": "Point", "coordinates": [ 11.52199, 3.79413 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "EKIE NORD" }, "geometry": { "type": "Point", "coordinates": [ 11.53559, 3.83238 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "AWAE IV" }, "geometry": { "type": "Point", "coordinates": [ 11.52559, 3.85135 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "AWAE II" }, "geometry": { "type": "Point", "coordinates": [ 11.52385, 3.85251 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "TOUTOULI" }, "geometry": { "type": "Point", "coordinates": [ 11.51024, 3.76814 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "EKOUNOU II" }, "geometry": { "type": "Point", "coordinates": [ 11.53941, 3.84444 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NKOMO II SUD" }, "geometry": { "type": "Point", "coordinates": [ 11.54793, 3.84314 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NKOLO" }, "geometry": { "type": "Point", "coordinates": [ 11.56846, 3.85711 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "AWAE MVOG MANGA" }, "geometry": { "type": "Point", "coordinates": [ 11.55431, 3.8304 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "mfoundassi V" }, "geometry": { "type": "Point", "coordinates": [ 11.52031, 3.84813 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "AWAE III" }, "geometry": { "type": "Point", "coordinates": [ 11.52545, 3.85124 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MFOUNDASSI II" }, "geometry": { "type": "Point", "coordinates": [ 11.5177, 3.84839 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NKOLDONGO VII" }, "geometry": { "type": "Point", "coordinates": [ 11.52695, 3.85282 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "Mfoundassi III" }, "geometry": { "type": "Point", "coordinates": [ 11.52061, 3.85148 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MEYO" }, "geometry": { "type": "Point", "coordinates": [ 11.50387, 3.78038 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NKOMO II NORD" }, "geometry": { "type": "Point", "coordinates": [ 11.54181, 3.84602 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "AWAE VI" }, "geometry": { "type": "Point", "coordinates": [ 11.52233, 3.8493 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "ESSOS NORD 2" }, "geometry": { "type": "Point", "coordinates": [ 11.541, 3.87647 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "ESSOS SUD 1" }, "geometry": { "type": "Point", "coordinates": [ 11.53658, 3.87012 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MFANDENA II" }, "geometry": { "type": "Point", "coordinates": [ 11.5436, 3.88799 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NGOULEMEKONG" }, "geometry": { "type": "Point", "coordinates": [ 11.56556, 3.90741 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NKOLMESSING II" }, "geometry": { "type": "Point", "coordinates": [ 11.557359, 3.88194 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MFANDENA I" }, "geometry": { "type": "Point", "coordinates": [ 11.53388, 3.8863 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NKOLMESSENG I" }, "geometry": { "type": "Point", "coordinates": [ 11.55821, 3.88834 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NKOL NKONDI I" }, "geometry": { "type": "Point", "coordinates": [ 11.56189, 3.91803 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "ESSOS SUD 2" }, "geometry": { "type": "Point", "coordinates": [ 11.54374, 3.87088 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NKOL BIKOK 1" }, "geometry": { "type": "Point", "coordinates": [ 11.49013, 3.87107 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NKOL BIKOK 2" }, "geometry": { "type": "Point", "coordinates": [ 11.49142, 3.86878 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "ETOUG-EBE 2" }, "geometry": { "type": "Point", "coordinates": [ 11.45915, 3.84415 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "ELIG-EFFA I" }, "geometry": { "type": "Point", "coordinates": [ 11.49783, 3.8701 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "SIMBOK" }, "geometry": { "type": "Point", "coordinates": [ 11.47271, 3.80444 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "ETETAK" }, "geometry": { "type": "Point", "coordinates": [ 11.48196, 3.87154 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "OYOMABANG I" }, "geometry": { "type": "Point", "coordinates": [ 11.47649, 3.87426 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "MINKOA MEYOS" }, "geometry": { "type": "Point", "coordinates": [ 11.42452, 3.87466 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "NKOL-AFEME" }, "geometry": { "type": "Point", "coordinates": [ 11.45637, 3.89065 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "Quartier ABOBO" }, "geometry": { "type": "Point", "coordinates": [ 11.47338, 3.87814 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "EBOT MEFOU" }, "geometry": { "type": "Point", "coordinates": [ 11.44337, 3.87415 ] } },
{ "type": "Feature", "properties": { "nom_lieu": "KOMASSI" }, "geometry": { "type": "Point", "coordinates": [ 11.4458, 3.85132 ] } }
]
}
